/**
 * FILE ENGINE - Push to GitHub API Route
 * 
 * POST /api/file-engine/push-github
 * 
 * Creates a GitHub repo and pushes files, or pushes to existing repo.
 */

import { NextRequest, NextResponse } from 'next/server';
import { BRAND_NAME } from '@/lib/brand'
import { 

  createRepoAndPush, 
  pushFiles, 
  checkRepoExists,
  getCurrentUser
} from '@/lib/file-engine/github-api';
import { supabase } from '@/lib/supabase';
import { validationErrorResponse } from '@/lib/schemas'

// ============================================
// TYPES
// ============================================

interface PushGitHubRequest {
  files: Array<{
    path: string;
    content: string;
  }>;

  repoOwner?: string;
  repoName: string;
  branch?: string;
  commitMessage?: string;
  githubToken?: string; // From user's connected account
  createIfNotExists?: boolean;
  isPrivate?: boolean;
}

// ============================================
// ROUTE HANDLER
// ============================================

export const dynamic = 'force-dynamic'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json() as Record<string, any>;
    
    // Validate request
    if (!body.files || !Array.isArray(body.files) || body.files.length === 0) {
      return NextResponse.json(
        { success: false, error: 'No files provided' },
        { status: 400 }
      );
    }

    if (!body.repoName || typeof body.repoName !== 'string') {
      return NextResponse.json(
        { success: false, error: 'Repository name is required' },
        { status: 400 }
      );
    }

    // Check file size limit (10MB total)
    const totalSize = body.files.reduce((acc, f) => acc + f.content.length, 0);
    if (totalSize > 10 * 1024 * 1024) {
      return NextResponse.json(
        { success: false, error: 'Total file size exceeds 10MB limit' },
        { status: 400 }
      );
    }

    // Use user's token if provided, otherwise admin token
    const githubToken = body.githubToken || 
                       process.env.GITHUB_TOKEN || 
                       process.env.ADMIN_GITHUB_TOKEN;

    // Permission gate: require deploy_github feature
    try {
      const { data: { session } } = await supabase.auth.getSession();
      const userId = session?.user?.id;
      if (userId) {
        const { hasFeature } = await import('@/lib/permissions')
        const allowed = await hasFeature(userId, 'deploy_github')
        if (!allowed) {
          return NextResponse.json(
            { success: false, error: 'Upgrade to Pro to push to GitHub', upsell: true },
            { status: 403 }
          )
        }
      }
    } catch { /* permission check non-fatal in dev */ }

    if (!githubToken) {
      return NextResponse.json(
        { success: false, error: 'GitHub token not configured' },
        { status: 500 }
      );
    }

    // Get the owner - either specified or from token
    let owner = body.repoOwner;
    if (!owner) {
      const user = await getCurrentUser({ token: githubToken });
      if (!user) {
        return NextResponse.json(
          { success: false, error: 'Could not determine GitHub username' },
          { status: 400 }
        );
      }
      owner = user.login;
    }

    // Sanitize repo name
    const sanitizedRepoName = body.repoName
      .toLowerCase()
      .replace(/\s+/g, '-')
      .replace(/[^a-z0-9-]/g, '')
      .slice(0, 100);

    // Check if repo exists
    const repoExists = await checkRepoExists(owner, sanitizedRepoName, { token: githubToken });

    let result;
    
    if (repoExists) {
      // Push to existing repo
      result = await pushFiles(owner, sanitizedRepoName, body.files, {
        branch: body.branch,
        commitMessage: body.commitMessage || `Update from ${BRAND_NAME}`,
        token: githubToken
      });

      if (result.success) {
        // Get user for saving deployment record
        const { data: { session } } = await supabase.auth.getSession();
        const userId = session?.user?.id;

        if (userId) {
          await supabase.from('file_engine_deployments').insert({
            user_id: userId,
            project_name: body.repoName,
            files: body.files,
            deployed_to: ['github'],
            github_url: `https://github.com/${owner}/${sanitizedRepoName}`
          });
        }

        return NextResponse.json({
          success: true,
          repoUrl: `https://github.com/${owner}/${sanitizedRepoName}`,
          commitSha: result.commitSha,
          commitUrl: result.commitUrl
        });
      } else {
        return NextResponse.json({
          success: false,
          error: result.error || 'Failed to push files'
        }, { status: 422 });
      }

    } else if (body.createIfNotExists !== false) {
      // Create new repo and push
      result = await createRepoAndPush(sanitizedRepoName, body.files, {
        description: `Generated by ${BRAND_NAME}`,
        private: body.isPrivate,
        commitMessage: body.commitMessage || `Initial commit from ${BRAND_NAME}`,
        token: githubToken
      });

      if (result.success) {
        // Get user for saving deployment record
        const { data: { session } } = await supabase.auth.getSession();
        const userId = session?.user?.id;

        if (userId) {
          await supabase.from('file_engine_deployments').insert({
            user_id: userId,
            project_name: body.repoName,
            files: body.files,
            deployed_to: ['github'],
            github_url: result.repoUrl
          });
        }

        return NextResponse.json({
          success: true,
          repoUrl: result.repoUrl,
          commitSha: result.commitSha,
          created: true
        });
      } else {
        return NextResponse.json({
          success: false,
          error: result.error || 'Failed to create repository'
        }, { status: 422 });
      }

    } else {
      return NextResponse.json({
        success: false,
        error: `Repository ${owner}/${sanitizedRepoName} does not exist`
      }, { status: 404 });
    }

  } catch (error) {
    console.error('Push to GitHub error:', error);
    return NextResponse.json(
      { 
        success: false, 
        error: error instanceof Error ? error.message : 'Internal server error' 
      },
      { status: 500 }
    );
  }
}
